models:
    mobilenet_34.67_66.84: models/mobilenet_34.67_66.84.onnx
cluster_center:
    0: mobilenet_34.67_66.84
model_cluster:
    mobilenet_34.67_66.84:  0
expected_accuracy:
    modela: # array of size 10
    - 0.89
    - 0.99
    - 0.78
    - 0.39
    - 0.89
    - 0.99
    - 0.98
    - 0.39
    - 0.89
    - 0.99
    modelb: # array of size 10
    - 0.89
    - 0.99
    - 0.18
    - 0.39
    - 0.89
    - 0.99
    - 0.78
    - 0.39
    - 0.89
    - 0.99
    modelc: # array of size 10
    - 0.89
    - 0.99
    - 0.38
    - 0.39
    - 0.89
    - 0.99
    - 0.78
    - 0.39
    - 0.49
    - 0.99
    modeld: # array of size 10
    - 0.89
    - 0.79
    - 0.78
    - 0.39
    - 0.89
    - 0.99
    - 0.78
    - 0.39
    - 0.899
    - 0.99
